# Sources

### Data Dictionaries

- CDC https://svi.cdc.gov/Documents/Data/2016_SVI_Data/SVI2016Documentation.pdf
- CHR https://www.countyhealthrankings.org/explore-health-rankings/rankings-data-documentation

### Kaggle

- https://www.kaggle.com/johnjdavisiv/us-counties-covid19-weather-sociohealth-data/kernels

- https://www.kaggle.com/kerneler/starter-us-counties-covid19-weather-b1179fb5-d

- https://www.kaggle.com/johnjdavisiv/us-counties-weather-health-covid19-data/output

In [40]:
df1 = pd.read_csv('data/US_counties_COVID19_health_weather_data.csv', delimiter=',')
df1

,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,lat,lon,...,min_temp_3d_avg,min_temp_5d_avg,min_temp_10d_avg,min_temp_15d_avg,dewpoint_3d_avg,dewpoint_5d_avg,dewpoint_10d_avg,dewpoint_15d_avg,date_stay_at_home_announced,date_stay_at_home_effective
0,2020-01-21,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,...,38.266667,38.92,38.44,36.146667,40.333333,41.64,40.74,37.973333,2020-03-23,2020-03-23
1,2020-01-22,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,...,39.233333,41.12,39.76,37.613333,42.633333,42.98,41.68,39.440000,2020-03-23,2020-03-23
2,2020-01-23,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,...,42.900000,41.74,41.15,38.226667,44.733333,43.72,42.47,40.120000,2020-03-23,2020-03-23
3,2020-01-24,Cook,Illinois,17031,1,0,no,no,41.840039,-87.816716,...,32.366667,30.02,27.43,24.886667,31.433333,28.50,25.00,22.693333,2020-03-20,2020-03-21
4,2020-01-24,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,...,44.600000,42.54,41.75,38.226667,46.000000,44.30,42.88,41.293333,2020-03-23,2020-03-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111359,2020-05-03,Sublette,Wyoming,56035,1,0,no,no,42.766905,-109.914721,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111360,2020-05-03,Sweetwater,Wyoming,56037,11,0,no,no,41.659538,-108.879567,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111361,2020-05-03,Teton,Wyoming,56039,67,1,no,no,43.934776,-110.589759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111362,2020-05-03,Uinta,Wyoming,56041,6,0,no,no,41.287648,-110.547639,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111363,2020-05-03,Washakie,Wyoming,56043,4,0,no,no,43.904970,-107.682819,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### bea.gov

- https://www.bea.gov/data/income-saving/personal-income-county-metro-and-other-areas
- https://www.bea.gov/data/gdp/gdp-county-metro-and-other-areas

### NYT

- https://developer.nytimes.com/apis
- https://github.com/nytimes/covid-19-data
- https://www.nytimes.com/interactive/2020/us/coronavirus-stay-at-home-order.html
- https://www.nytimes.com/interactive/2020/us/states-reopen-map-coronavirus.html

### Johns Hopkins

- https://github.com/CSSEGISandData/COVID-19

### CDC.gov (COVID-19 data)

- https://www.cdc.gov/coronavirus/2019-ncov/cases-updates/county-map.html

### Kaiser Family Foundation (Stay at home order dates)

- https://www.kff.org/coronavirus-policy-watch/stay-at-home-orders-to-fight-covid19/

- https://abcnews.go.com/US/list-states-stay-home-order-lifts/story?id=70317035

https://www.littler.com/publication-press/publication/stay-top-stay-home-list-statewide

### census.gov(demographic data)

- https://www.census.gov/data/datasets.html
- https://www.census.gov/hhes/www/housing/resseg/pdf/app_b.pdf (segregation index calcuation)

### politico (voting data)

- https://www.politico.com/2016-election/results/map/president/texas/

['Overall 2016 Delaware Presidential Election Results\n100% Reporting   Electoral Votes: 3\nPolls Closing: 8:00 PM ET\nElectoral Votes\nD\nH. Clinton\n53.4%\n235,581 3\nR D. Trump\n41.9%\n185,103\nL G. Johnson\n3.3%\n14,751\nG J. Stein\n1.4%\n6,100\n* Runoff',
 'Kent County\n100% Reporting\nR D. Trump\n49.8%\n36,989\nD H. Clinton\n44.9%\n33,347\nL G. Johnson\n3.9%\n2,876\nG J. Stein\n1.4%\n1,041',
 'New Castle County\n100% Reporting\nD H. Clinton\n62.3%\n162,905\nR D. Trump\n32.7%\n85,507\nL G. Johnson\n3.5%\n9,101\nG J. Stein\n1.5%\n3,955',
 'Sussex County\n100% Reporting\nR D. Trump\n59.2%\n62,607\nD H. Clinton\n37.2%\n39,329\nL G. Johnson\n2.6%\n2,774\nG J. Stein\n1.0%\n1,104']

### archives.gov (demographic data, pew survey data regarding social attitudes)

### fcc.gov broadband data

In [28]:
#!/usr/bin/env python

# make sure to install these packages before running:
#pip install pandas
# pip install sodapy

import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("opendata.fcc.gov", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(opendata.fcc.gov,
#                  MyAppToken,
#                  userame="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("tun5-dwjh", type= 'county', limit = 3000000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

In [38]:
results_df

,type,id,tech,urban_rural,tribal_non,speed,has_0,has_1,has_2,has_3more
0,county,01001,acfosw,R,N,0.2,0,0,0,23790
1,county,01001,acfosw,U,N,0.2,0,0,0,31811
2,county,01003,acfosw,R,N,0.2,0,0,6,97711
3,county,01003,acfosw,U,N,0.2,0,0,1,120303
4,county,01005,acfosw,R,N,0.2,0,0,0,16437
...,...,...,...,...,...,...,...,...,...,...
2760655,county,78010,w,U,N,1000,46243,0,0,0
2760656,county,78020,w,R,N,1000,1108,0,0,0
2760657,county,78020,w,U,N,1000,3084,0,0,0
2760658,county,78030,w,R,N,1000,827,0,0,0
2760659,county,78030,w,U,N,1000,51085,0,0,0

### healthypeople.gov (healthcare data but typically not parsed by region so may have limited applicability)

### healthit.gov (statewide adoption of health it in hospital and ambulatory settings, API also available, would need to apply to all counties in state, not sure if that's a good idea)

### cms.gov (information about geographic requirements for telehealth reimbursements prior to COVID, potentially indicating readiness for switch to telehealth model by many healthcare providers)

### healthdata.gov (data on healthcare availability and usage)