In [1]:
import pandas as pd

In [27]:
df = pd.read_csv('data/US_counties_COVID19_health_weather_data.csv', delimiter=',')
df

/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,lat,lon,...,min_temp_3d_avg,min_temp_5d_avg,min_temp_10d_avg,min_temp_15d_avg,dewpoint_3d_avg,dewpoint_5d_avg,dewpoint_10d_avg,dewpoint_15d_avg,date_stay_at_home_announced,date_stay_at_home_effective
0,2020-01-21,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,...,38.266667,38.92,38.44,36.146667,40.333333,41.64,40.74,37.973333,2020-03-23,2020-03-23
1,2020-01-22,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,...,39.233333,41.12,39.76,37.613333,42.633333,42.98,41.68,39.440000,2020-03-23,2020-03-23
2,2020-01-23,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,...,42.900000,41.74,41.15,38.226667,44.733333,43.72,42.47,40.120000,2020-03-23,2020-03-23
3,2020-01-24,Cook,Illinois,17031,1,0,no,no,41.840039,-87.816716,...,32.366667,30.02,27.43,24.886667,31.433333,28.50,25.00,22.693333,2020-03-20,2020-03-21
4,2020-01-24,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,...,44.600000,42.54,41.75,38.226667,46.000000,44.30,42.88,41.293333,2020-03-23,2020-03-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111359,2020-05-03,Sublette,Wyoming,56035,1,0,no,no,42.766905,-109.914721,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111360,2020-05-03,Sweetwater,Wyoming,56037,11,0,no,no,41.659538,-108.879567,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111361,2020-05-03,Teton,Wyoming,56039,67,1,no,no,43.934776,-110.589759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111362,2020-05-03,Uinta,Wyoming,56041,6,0,no,no,41.287648,-110.547639,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111363,2020-05-03,Washakie,Wyoming,56043,4,0,no,no,43.904970,-107.682819,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
for column in df.columns:
    print (column)

county
state
fips
population_density_per_sqmi
num_deaths
percent_fair_or_poor_health
average_number_of_physically_unhealthy_days
percent_smokers
percent_adults_with_obesity
percent_physically_inactive
percent_with_access_to_exercise_opportunities
percent_excessive_drinking
num_alcohol_impaired_driving_deaths
num_driving_deaths
percent_driving_deaths_with_alcohol_involvement
num_chlamydia_cases
chlamydia_rate
teen_birth_rate
num_uninsured
percent_uninsured
num_primary_care_physicians
primary_care_physicians_rate
num_dentists
dentist_rate
num_mental_health_providers
mental_health_provider_rate
preventable_hospitalization_rate
percent_with_annual_mammogram
percent_vaccinated
high_school_graduation_rate
num_some_college
population
percent_some_college
num_unemployed_CHR
labor_force
percent_unemployed_CHR
percent_children_in_poverty
eightieth_percentile_income
twentieth_percentile_income
income_ratio
num_single_parent_households_CHR
num_households_CHR
percent_single_parent_households_CHR
num_associations
social_association_rate
annual_average_violent_crimes
violent_crime_rate
num_injury_deaths
injury_death_rate
average_daily_pm2_5
presence_of_water_violation
percent_severe_housing_problems
severe_housing_cost_burden
overcrowding
inadequate_facilities
percent_drive_alone_to_work
num_workers_who_drive_alone
percent_long_commute_drives_alone
life_expectancy
num_deaths_2
age_adjusted_death_rate
num_deaths_3
child_mortality_rate
num_deaths_4
infant_mortality_rate
percent_frequent_physical_distress
percent_frequent_mental_distress
percent_adults_with_diabetes
num_hiv_cases
hiv_prevalence_rate
num_food_insecure
percent_food_insecure
num_limited_access
percent_limited_access_to_healthy_foods
num_drug_overdose_deaths
drug_overdose_mortality_rate
num_motor_vehicle_deaths
motor_vehicle_mortality_rate
percent_insufficient_sleep
num_uninsured_2
percent_uninsured_2
num_uninsured_3
percent_uninsured_3
other_primary_care_provider_rate
percent_disconnected_youth
average_grade_performance
average_grade_performance_2
median_household_income
percent_enrolled_in_free_or_reduced_lunch
segregation_index
segregation_index_2
homicide_rate
num_deaths_5
suicide_rate_age_adjusted
num_firearm_fatalities
firearm_fatalities_rate
juvenile_arrest_rate
average_traffic_volume_per_meter_of_major_roadways
num_homeowners
percent_homeowners
num_households_with_severe_cost_burden
percent_severe_housing_cost_burden
population_2
percent_less_than_18_years_of_age
percent_65_and_over
num_black
percent_black
num_american_indian_alaska_native
percent_american_indian_alaska_native
num_asian
percent_asian
num_native_hawaiian_other_pacific_islander
percent_native_hawaiian_other_pacific_islander
num_hispanic
percent_hispanic
num_non_hispanic_white
percent_non_hispanic_white
num_not_proficient_in_english
percent_not_proficient_in_english
percent_female
num_rural
percent_rural
num_housing_units
num_households_CDC
num_below_poverty
num_unemployed_CDC
per_capita_income
num_no_highschool_diploma
num_age_65_and_older
num_age_17_and_younger
num_disabled
num_single_parent_households_CDC
num_minorities
num_limited_english_abilities
num_multi_unit_housing
num_mobile_homes
num_overcrowding
num_households_with_no_vehicle
num_institutionalized_in_group_quarters
percent_below_poverty
percent_unemployed_CDC
percent_no_highschool_diploma
percent_age_65_and_older
percent_age_17_and_younger
percent_disabled
percent_single_parent_households_CDC
percent_minorities
percent_limited_english_abilities
percent_multi_unit_housing
percent_mobile_homes
percent_overcrowding
percent_no_vehicle
percent_institutionalized_in_group_quarters
percentile_rank_below_poverty
percentile_rank_unemployed
percentile_rank_per_capita_income
percentile_rank_no_highschool_diploma
percentile_rank_socioeconomic_theme
percentile_rank_age_65_and_older
percentile_rank_age_17_and_younger
percentile_rank_disabled
percentile_rank_single_parent_households
percentile_rank_household_comp_disability_theme
percentile_rank_minorities
percentile_rank_limited_english_abilities
percentile_rank_minority_status_and_language_theme
percentile_rank_multi_unit_housing
percentile_rank_mobile_homes
percentile_rank_overcrowding
percentile_rank_no_vehicle
percentile_rank_institutionalized_in_group_quarters
percentile_rank_housing_and_transportation
percentile_rank_social_vulnerability
km_to_closest_station
CALL
ELEV_M
station_id
station_name
mean_temp
date_stay_at_home_announced
date_stay_at_home_effective

In [116]:
df2 = df[['county','state','fips','population_density_per_sqmi','percent_fair_or_poor_health',
          'percent_smokers','percent_adults_with_obesity','percent_physically_inactive','percent_uninsured',
          'primary_care_physicians_rate','percent_vaccinated','life_expectancy',
          'percent_adults_with_diabetes','percent_insufficient_sleep', 'percent_disabled',
          'other_primary_care_provider_rate','median_household_income',
          'segregation_index_2','percent_less_than_18_years_of_age','percent_65_and_over',
          'percent_not_proficient_in_english','percent_female','percent_rural','per_capita_income',
          'percent_below_poverty','percent_unemployed_CDC','percent_age_65_and_older',
          'percent_age_17_and_younger','percent_minorities','percent_multi_unit_housing',
          'date_stay_at_home_announced','date_stay_at_home_effective']]

In [117]:
df3 = df2.drop_duplicates()

In [118]:
df3

,county,state,fips,population_density_per_sqmi,percent_fair_or_poor_health,percent_smokers,percent_adults_with_obesity,percent_physically_inactive,percent_uninsured,primary_care_physicians_rate,...,percent_rural,per_capita_income,percent_below_poverty,percent_unemployed_CDC,percent_age_65_and_older,percent_age_17_and_younger,percent_minorities,percent_multi_unit_housing,date_stay_at_home_announced,date_stay_at_home_effective
0,Snohomish,Washington,53061,363.586159,14.403971,12.962309,28.9,17.8,6.207640,52.51780,...,10.819461,33883.0,9.3,6.2,12.1,23.2,28.0,14.6,2020-03-23,2020-03-23
3,Cook,Illinois,17031,5531.878539,17.140851,13.776183,28.0,21.0,9.972268,93.31711,...,0.045296,32179.0,16.7,9.7,13.0,22.7,57.1,23.0,2020-03-20,2020-03-21
5,Orange,California,06059,3961.705072,13.902378,9.311197,19.4,15.2,8.336576,97.41725,...,0.143344,35939.0,12.5,6.8,13.2,23.0,58.0,18.7,2020-03-19,2020-03-19
8,Maricopa,Arizona,04013,444.446744,15.622654,13.686398,26.9,20.4,12.081176,70.35005,...,2.363800,28791.0,16.5,6.8,13.8,25.0,43.1,14.6,2020-03-30,2020-03-31
9,Los Angeles,California,06037,2478.240645,16.418669,10.847678,21.7,16.4,10.059485,72.78000,...,0.605218,29301.0,17.8,8.9,12.2,22.8,73.3,26.5,2020-03-19,2020-03-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111359,Sublette,Wyoming,56035,2.053012,12.237396,13.912994,29.9,22.4,14.601549,51.02561,...,100.000000,30295.0,7.8,2.8,13.3,24.1,8.4,0.3,NaN,NaN
111360,Sweetwater,Wyoming,56037,4.297803,14.813082,18.073422,29.8,25.0,14.464995,36.75288,...,10.916313,30945.0,11.0,5.1,9.4,27.5,20.2,6.0,NaN,NaN
111361,Teton,Wyoming,56039,5.661502,11.914358,14.546369,12.4,11.6,16.034517,116.05416,...,46.430920,46499.0,7.3,2.1,11.8,19.5,18.8,6.6,NaN,NaN
111362,Uinta,Wyoming,56041,10.035892,15.537464,17.212675,35.8,27.2,13.664737,43.91315,...,43.095937,25636.0,16.8,6.4,10.7,29.6,12.3,6.2,NaN,NaN
111363,Washakie,Wyoming,56043,3.730539,15.955971,16.859400,28.8,28.2,16.730280,49.60317,...,35.954529,26325.0,14.7,7.4,19.7,24.8,17.6,1.8,NaN,NaN

In [125]:
df4 = df3.groupby(['county', 'state','fips', 'date_stay_at_home_announced','date_stay_at_home_effective']).mean()

df4.to_csv('data/first_cleaning.csv')

In [146]:
df5 = pd.read_csv('first_cleaning.csv')

df5['fips'].value_counts()

53061    2
42133    2
51570    2
48065    2
48239    2
        ..
20073    1
17001    1
30003    1
26119    1
26089    1
Name: fips, Length: 2388, dtype: int64

In [147]:
df6 = df5.drop_duplicates()

In [148]:
df6['fips'].value_counts()

21007    1
48187    1
26049    1
28131    1
20087    1
        ..
51620    1
48039    1
18087    1
2150     1
26089    1
Name: fips, Length: 2388, dtype: int64

In [150]:
df6.to_csv('second_cleaning.csv', index = False)

In [151]:
test2_df['fips'].value_counts()

17031    92
53061    86
06037    85
04013    83
55025    82
         ..
48201     1
48203     1
31089     1
48169     1
46081     1
Name: fips, Length: 3641, dtype: int64

In [91]:
test2_df.to_csv('data/for_spark')

In [96]:
df['fips'].value_counts()

53061    103
17031    101
06059    100
06037     99
04013     99
        ...
46035      1
46037      1
46039      1
46041      1
46087      1
Name: fips, Length: 3641, dtype: int64

8       1.0
15      1.0
206     1.0
293     1.0
434     1.0
       ...
3207    1.0
3208    1.0
3209    1.0
3210    1.0
3211    1.0
Length: 348, dtype: float64

In [145]:
df_cleaner.to_csv('data/df_first_clean', index = False)

FileNotFoundError: [Errno 2] No such file or directory: 'data/df_first_clean'