In [6]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, roc_curve, precision_score, recall_score
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression

In [101]:
df = pd.read_csv('data/second_cleaning.csv')

In [102]:
df

,county,state,fips,date_stay_at_home_announced,date_stay_at_home_effective,population_density_per_sqmi,percent_fair_or_poor_health,percent_smokers,percent_adults_with_obesity,percent_physically_inactive,...,percent_not_proficient_in_english,percent_female,percent_rural,per_capita_income,percent_below_poverty,percent_unemployed_CDC,percent_age_65_and_older,percent_age_17_and_younger,percent_minorities,percent_multi_unit_housing
0,Acadia,Louisiana,22001,3/22/20,3/23/20,95.205636,20.890035,21.534088,38.4,35.3,...,1.245549,51.210806,51.698962,20887.0,20.6,9.1,13.5,26.8,22.2,2.2
1,Accomack,Virginia,51001,3/30/20,3/30/20,73.579904,20.089199,18.316929,36.3,36.1,...,4.205986,51.200173,100.000000,23337.0,19.5,7.0,21.0,20.9,39.4,2.1
2,Ada,Idaho,16001,3/25/20,3/25/20,404.551458,11.474882,11.990701,25.6,14.9,...,1.268973,49.939783,5.472201,30086.0,12.2,5.3,12.6,25.1,14.5,7.4
3,Adair,Kentucky,21001,3/22/20,3/26/20,47.265760,22.848614,22.619973,40.9,33.1,...,0.241321,50.517825,75.455618,18463.0,23.3,5.8,16.7,20.4,6.5,2.3
4,Adair,Missouri,29001,4/3/20,4/6/20,45.030735,21.401500,20.528843,27.9,31.7,...,2.152414,51.876554,37.852931,19804.0,26.0,6.5,14.0,18.5,9.2,4.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2383,Yukon-Koyukuk Census Area,Alaska,2290,3/27/20,3/28/20,0.038490,22.928933,29.691434,30.5,24.0,...,0.139665,47.024592,100.000000,20812.0,23.5,18.4,13.4,27.9,78.8,0.5
2384,Yuma,Arizona,4027,3/30/20,3/31/20,36.868166,22.726376,13.327036,36.9,26.3,...,14.117653,48.471677,10.429576,19483.0,20.5,12.5,17.4,26.2,67.3,4.7
2385,Yuma,Colorado,8125,3/26/20,3/26/20,4.292849,15.268202,14.277809,27.8,21.3,...,6.508176,50.209581,64.910883,23905.0,14.6,2.2,17.9,27.1,23.2,3.9
2386,Zapata,Texas,48505,3/31/20,4/2/20,14.357800,35.610705,17.275488,31.2,19.7,...,24.389116,50.084567,23.534028,16007.0,34.1,12.6,11.7,33.8,94.1,0.5
2387,Zavala,Texas,48507,3/31/20,4/2/20,9.331695,40.990687,19.871284,24.2,20.0,...,7.977869,49.420012,38.032029,13393.0,35.8,12.0,12.5,30.5,94.2,1.1

In [103]:
df.sort_values('fips', inplace = True, ignore_index = True)

In [104]:
df

,county,state,fips,date_stay_at_home_announced,date_stay_at_home_effective,population_density_per_sqmi,percent_fair_or_poor_health,percent_smokers,percent_adults_with_obesity,percent_physically_inactive,...,percent_not_proficient_in_english,percent_female,percent_rural,per_capita_income,percent_below_poverty,percent_unemployed_CDC,percent_age_65_and_older,percent_age_17_and_younger,percent_minorities,percent_multi_unit_housing
0,Kent,Delaware,10001,3/22/20,3/24/20,292.457188,18.955716,16.823760,35.400000,31.200000,...,1.353224,51.821339,26.969380,26118.00000,13.200000,8.000000,15.500000,23.600000,36.700000,7.300000
1,New Castle,Delaware,10003,3/22/20,3/24/20,1294.800627,16.799934,15.242558,28.700000,25.500000,...,2.074491,51.527618,4.602408,33240.00000,11.400000,6.900000,13.800000,22.200000,40.800000,13.500000
2,Sussex,Delaware,10005,3/22/20,3/24/20,225.644458,17.813709,16.085001,32.900000,30.300000,...,2.349873,51.684359,41.303609,29630.00000,12.900000,7.100000,24.200000,19.600000,25.200000,5.500000
3,Autauga,Alabama,1001,4/3/20,4/4/20,92.605533,20.882987,18.081557,33.300000,34.700000,...,0.820225,51.448715,42.002162,26168.00000,12.300000,5.600000,14.000000,25.200000,24.300000,4.600000
4,Baldwin,Alabama,1003,4/3/20,4/4/20,125.493187,17.509134,17.489033,31.000000,26.500000,...,0.543517,51.538377,42.279099,28069.00000,13.000000,6.300000,18.700000,22.200000,16.800000,18.300000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2383,New London,Connecticut,9011,3/20/20,3/23/20,408.984791,11.546282,12.350840,29.600000,20.900000,...,2.215244,49.883801,25.808323,35531.00000,9.900000,7.700000,16.100000,20.300000,23.500000,8.800000
2384,Tolland,Connecticut,9013,3/20/20,3/23/20,369.682148,10.470405,10.543490,24.900000,19.100000,...,0.757905,49.908893,38.207884,36364.00000,6.800000,6.300000,13.900000,18.600000,14.100000,7.700000
2385,Windham,Connecticut,9015,3/20/20,3/23/20,228.277233,13.385188,14.356952,30.300000,23.000000,...,2.369814,50.487494,49.761036,28663.00000,11.200000,8.400000,14.600000,20.700000,16.200000,4.600000
2386,Kansas City,Missouri,KSC,4/3/20,4/6/20,525.284248,16.402077,18.714348,32.581804,23.339531,...,1.511567,51.361780,8.710926,29129.56243,13.922539,6.115614,13.475149,24.350060,29.126142,11.572662
2387,New York City,New York,NYC,3/20/20,3/22/20,28069.675980,17.482725,13.393412,21.516529,24.495824,...,10.991914,52.153204,0.000443,34099.49507,20.279617,8.738277,13.010395,21.194835,67.750645,51.212050

In [105]:
df_kcny = df.iloc[-2:]

In [106]:
df = df.iloc[:-2]

In [107]:
df

,county,state,fips,date_stay_at_home_announced,date_stay_at_home_effective,population_density_per_sqmi,percent_fair_or_poor_health,percent_smokers,percent_adults_with_obesity,percent_physically_inactive,...,percent_not_proficient_in_english,percent_female,percent_rural,per_capita_income,percent_below_poverty,percent_unemployed_CDC,percent_age_65_and_older,percent_age_17_and_younger,percent_minorities,percent_multi_unit_housing
0,Kent,Delaware,10001,3/22/20,3/24/20,292.457188,18.955716,16.823760,35.4,31.2,...,1.353224,51.821339,26.969380,26118.0,13.2,8.0,15.5,23.6,36.7,7.3
1,New Castle,Delaware,10003,3/22/20,3/24/20,1294.800627,16.799934,15.242558,28.7,25.5,...,2.074491,51.527618,4.602408,33240.0,11.4,6.9,13.8,22.2,40.8,13.5
2,Sussex,Delaware,10005,3/22/20,3/24/20,225.644458,17.813709,16.085001,32.9,30.3,...,2.349873,51.684359,41.303609,29630.0,12.9,7.1,24.2,19.6,25.2,5.5
3,Autauga,Alabama,1001,4/3/20,4/4/20,92.605533,20.882987,18.081557,33.3,34.7,...,0.820225,51.448715,42.002162,26168.0,12.3,5.6,14.0,25.2,24.3,4.6
4,Baldwin,Alabama,1003,4/3/20,4/4/20,125.493187,17.509134,17.489033,31.0,26.5,...,0.543517,51.538377,42.279099,28069.0,13.0,6.3,18.7,22.2,16.8,18.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2381,Middlesex,Connecticut,9007,3/20/20,3/23/20,445.265514,10.377224,11.316441,25.5,19.4,...,1.208969,51.290247,24.540066,42573.0,7.0,5.3,17.7,19.2,15.3,9.0
2382,New Haven,Connecticut,9009,3/20/20,3/23/20,1424.105722,14.442711,12.843952,28.1,21.7,...,3.373222,51.785873,3.639981,33706.0,12.8,8.5,15.6,21.1,35.2,14.0
2383,New London,Connecticut,9011,3/20/20,3/23/20,408.984791,11.546282,12.350840,29.6,20.9,...,2.215244,49.883801,25.808323,35531.0,9.9,7.7,16.1,20.3,23.5,8.8
2384,Tolland,Connecticut,9013,3/20/20,3/23/20,369.682148,10.470405,10.543490,24.9,19.1,...,0.757905,49.908893,38.207884,36364.0,6.8,6.3,13.9,18.6,14.1,7.7
2385,Windham,Connecticut,9015,3/20/20,3/23/20,228.277233,13.385188,14.356952,30.3,23.0,...,2.369814,50.487494,49.761036,28663.0,11.2,8.4,14.6,20.7,16.2,4.6

In [197]:
target_df = pd.read_csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv')

1        17560
2        10402
3         8290
4         6218
5         5047
         ...
32724        1
33983        1
14173        1
5549         1
2047         1
Name: cases, Length: 4082, dtype: int64

In [182]:
grouped_df = target_df.groupby(['fips']).sum()

In [183]:
grouped_df

         cases  deaths
fips
1001.0    1427      82
1003.0    5163     110
1005.0    1057      13
1007.0    1142       4
1009.0    1081       0
...        ...     ...
56035.0    110       0
56037.0    566       0
56039.0   3380      19
56041.0    232       0
56043.0    259       0

[2885 rows x 2 columns]

In [184]:
grouped_df.to_csv('target.csv')

In [185]:
target_df = pd.read_csv('target.csv')

In [191]:
target_df.dtypes

fips      float64
cases       int64
deaths      int64
dtype: object

In [192]:
target_df.sort_values('fips', inplace= True, ignore_index = True)

In [193]:
target_df

         fips  cases  deaths
0      1001.0   1427      82
1      1003.0   5163     110
2      1005.0   1057      13
3      1007.0   1142       4
4      1009.0   1081       0
...       ...    ...     ...
2880  56035.0    110       0
2881  56037.0    566       0
2882  56039.0   3380      19
2883  56041.0    232       0
2884  56043.0    259       0

[2885 rows x 3 columns]

In [194]:
y1 = target_df['cases'].values

In [195]:
y2 = target_df['deaths'].values

In [200]:
y3 = (target_df['deaths']/target_df['Population']).values

KeyError: 'Population'

In [93]:
df.sort_values('fips', inplace = True, ignore_index = True)

In [124]:
df1 = pd.merge(df, target_df, how='inner', on = 'fips')

In [126]:
df1

,county_x,state_x,fips,date_stay_at_home_announced,date_stay_at_home_effective,population_density_per_sqmi,percent_fair_or_poor_health,percent_smokers,percent_adults_with_obesity,percent_physically_inactive,...,percent_below_poverty,percent_unemployed_CDC,percent_age_65_and_older,percent_age_17_and_younger,percent_minorities,percent_multi_unit_housing,county_y,state_y,cases,deaths
0,Kent,Delaware,10001.0,3/22/20,3/24/20,292.457188,18.955716,16.823760,35.4,31.2,...,13.2,8.0,15.5,23.6,36.7,7.3,Kent,Delaware,19927,636
1,New Castle,Delaware,10003.0,3/22/20,3/24/20,1294.800627,16.799934,15.242558,28.7,25.5,...,11.4,6.9,13.8,22.2,40.8,13.5,New Castle,Delaware,52154,1729
2,Sussex,Delaware,10005.0,3/22/20,3/24/20,225.644458,17.813709,16.085001,32.9,30.3,...,12.9,7.1,24.2,19.6,25.2,5.5,Sussex,Delaware,53016,1432
3,Autauga,Alabama,1001.0,4/3/20,4/4/20,92.605533,20.882987,18.081557,33.3,34.7,...,12.3,5.6,14.0,25.2,24.3,4.6,Autauga,Alabama,1343,78
4,Baldwin,Alabama,1003.0,4/3/20,4/4/20,125.493187,17.509134,17.489033,31.0,26.5,...,13.0,6.3,18.7,22.2,16.8,18.3,Baldwin,Alabama,4939,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372,Middlesex,Connecticut,9007.0,3/20/20,3/23/20,445.265514,10.377224,11.316441,25.5,19.4,...,7.0,5.3,17.7,19.2,15.3,9.0,Middlesex,Connecticut,18722,1997
2373,New Haven,Connecticut,9009.0,3/20/20,3/23/20,1424.105722,14.442711,12.843952,28.1,21.7,...,12.8,8.5,15.6,21.1,35.2,14.0,New Haven,Connecticut,206415,12866
2374,New London,Connecticut,9011.0,3/20/20,3/23/20,408.984791,11.546282,12.350840,29.6,20.9,...,9.9,7.7,16.1,20.3,23.5,8.8,New London,Connecticut,15219,863
2375,Tolland,Connecticut,9013.0,3/20/20,3/23/20,369.682148,10.470405,10.543490,24.9,19.1,...,6.8,6.3,13.9,18.6,14.1,7.7,Tolland,Connecticut,12526,1129
2376,Windham,Connecticut,9015.0,3/20/20,3/23/20,228.277233,13.385188,14.356952,30.3,23.0,...,11.2,8.4,14.6,20.7,16.2,4.6,Windham,Connecticut,5123,99

In [127]:
df1.isnull().sum()

county_x                               0
state_x                                0
fips                                   0
date_stay_at_home_announced            0
date_stay_at_home_effective            0
population_density_per_sqmi            0
percent_fair_or_poor_health            0
percent_smokers                        0
percent_adults_with_obesity            0
percent_physically_inactive            0
percent_uninsured                      0
primary_care_physicians_rate          81
percent_vaccinated                     5
life_expectancy                       17
percent_adults_with_diabetes           0
percent_insufficient_sleep             0
percent_disabled                       0
other_primary_care_provider_rate      18
median_household_income                0
segregation_index_2                  122
percent_less_than_18_years_of_age      0
percent_65_and_over                    0
percent_not_proficient_in_english      0
percent_female                         0
percent_rural                          2
per_capita_income                      0
percent_below_poverty                  0
percent_unemployed_CDC                 0
percent_age_65_and_older               0
percent_age_17_and_younger             0
percent_minorities                     0
percent_multi_unit_housing             0
county_y                               0
state_y                                0
cases                                  0
deaths                                 0
dtype: int64

In [143]:
df1['date_stay_at_home_announced'] = pd.to_datetime(df1['date_stay_at_home_announced'])

In [144]:
df1['date_stay_at_home_effective'] = pd.to_datetime(df1['date_stay_at_home_effective'])

In [152]:
sort_dates_df = df1['date_stay_at_home_announced'].sort_values()

sort_dates_df

2261   2020-03-19
2286   2020-03-19
2285   2020-03-19
2284   2020-03-19
2283   2020-03-19
          ...
1138   2020-04-03
52     2020-04-03
51     2020-04-03
59     2020-04-03
46     2020-04-03
Name: date_stay_at_home_announced, Length: 2377, dtype: datetime64[ns]

In [153]:
def daterange(start_date, end_date):
    for n in range(int ((end_date - start_date).days)):
        yield start_date + timedelta(n)

In [154]:
announced = df1['date_stay_at_home_announced']
effective = df1['date_stay_at_home_effective']

In [130]:
df1.drop(columns = ['county_x', 'state_x', 'county_y', 'state_y'], inplace = True)

In [146]:
df1

,fips,date_stay_at_home_announced,date_stay_at_home_effective,population_density_per_sqmi,percent_fair_or_poor_health,percent_smokers,percent_adults_with_obesity,percent_physically_inactive,percent_uninsured,primary_care_physicians_rate,...,percent_rural,per_capita_income,percent_below_poverty,percent_unemployed_CDC,percent_age_65_and_older,percent_age_17_and_younger,percent_minorities,percent_multi_unit_housing,cases,deaths
0,10001.0,2020-03-22,2020-03-24,292.457188,18.955716,16.823760,35.4,31.2,6.407516,46.37380,...,26.969380,26118.0,13.2,8.0,15.5,23.6,36.7,7.3,19927,636
1,10003.0,2020-03-22,2020-03-24,1294.800627,16.799934,15.242558,28.7,25.5,5.595841,83.78097,...,4.602408,33240.0,11.4,6.9,13.8,22.2,40.8,13.5,52154,1729
2,10005.0,2020-03-22,2020-03-24,225.644458,17.813709,16.085001,32.9,30.3,7.154550,62.13330,...,41.303609,29630.0,12.9,7.1,24.2,19.6,25.2,5.5,53016,1432
3,1001.0,2020-04-03,2020-04-04,92.605533,20.882987,18.081557,33.3,34.7,8.721686,45.04180,...,42.002162,26168.0,12.3,5.6,14.0,25.2,24.3,4.6,1343,78
4,1003.0,2020-04-03,2020-04-04,125.493187,17.509134,17.489033,31.0,26.5,11.333404,72.89727,...,42.279099,28069.0,13.0,6.3,18.7,22.2,16.8,18.3,4939,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372,9007.0,2020-03-20,2020-03-23,445.265514,10.377224,11.316441,25.5,19.4,4.090509,70.98709,...,24.540066,42573.0,7.0,5.3,17.7,19.2,15.3,9.0,18722,1997
2373,9009.0,2020-03-20,2020-03-23,1424.105722,14.442711,12.843952,28.1,21.7,5.689899,87.86253,...,3.639981,33706.0,12.8,8.5,15.6,21.1,35.2,14.0,206415,12866
2374,9011.0,2020-03-20,2020-03-23,408.984791,11.546282,12.350840,29.6,20.9,5.006681,64.30438,...,25.808323,35531.0,9.9,7.7,16.1,20.3,23.5,8.8,15219,863
2375,9013.0,2020-03-20,2020-03-23,369.682148,10.470405,10.543490,24.9,19.1,3.741395,50.17793,...,38.207884,36364.0,6.8,6.3,13.9,18.6,14.1,7.7,12526,1129
2376,9015.0,2020-03-20,2020-03-23,228.277233,13.385188,14.356952,30.3,23.0,5.604026,45.54869,...,49.761036,28663.0,11.2,8.4,14.6,20.7,16.2,4.6,5123,99

In [134]:
y = (df1['deaths']/df1['cases']).values

In [135]:
y

array([0.0319165 , 0.03315182, 0.02701071, ..., 0.05670543, 0.09013252,
       0.01932461])

In [162]:
Xdf = df1.drop(columns = ['cases', 'deaths', 'date_stay_at_home_announced', 'date_stay_at_home_effective', 
                          'primary_care_physicians_rate', 'other_primary_care_provider_rate', 'segregation_index_2'
                         ])

In [163]:
X = Xdf.values

In [164]:
Xdf.isnull().sum()

fips                                  0
population_density_per_sqmi           0
percent_fair_or_poor_health           0
percent_smokers                       0
percent_adults_with_obesity           0
percent_physically_inactive           0
percent_uninsured                     0
percent_vaccinated                    5
life_expectancy                      17
percent_adults_with_diabetes          0
percent_insufficient_sleep            0
percent_disabled                      0
median_household_income               0
percent_less_than_18_years_of_age     0
percent_65_and_over                   0
percent_not_proficient_in_english     0
percent_female                        0
percent_rural                         2
per_capita_income                     0
percent_below_poverty                 0
percent_unemployed_CDC                0
percent_age_65_and_older              0
percent_age_17_and_younger            0
percent_minorities                    0
percent_multi_unit_housing            0
dtype: int64

In [165]:
Xdf['percent_vaccinated'].fillna(Xdf['percent_vaccinated'].mean(skipna = True), inplace = True)

In [166]:
Xdf['life_expectancy'].fillna(Xdf['life_expectancy'].mean(skipna = True), inplace = True)

In [167]:
Xdf['percent_rural'].fillna(Xdf['percent_rural'].mean(skipna = True), inplace = True)

In [168]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [172]:
rf = RandomForestRegressor()
rf.fit(X_train, y_train)

rf.score(X_test, y_test)

-0.05541783911430432