In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import cross_val_score, train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, roc_curve, precision_score, recall_score
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression

In [2]:
target_df = pd.read_csv('target.csv')

In [3]:
target_df.sort_values('fips', inplace= True, ignore_index = True)

In [4]:
target_df

         fips  cases  deaths
0      1001.0   1427      82
1      1003.0   5163     110
2      1005.0   1057      13
3      1007.0   1142       4
4      1009.0   1081       0
...       ...    ...     ...
2880  56035.0    110       0
2881  56037.0    566       0
2882  56039.0   3380      19
2883  56041.0    232       0
2884  56043.0    259       0

[2885 rows x 3 columns]

In [18]:
df = pd.read_csv('data/tues_clean1.csv')

In [22]:
df.rename(columns = {'FIPS': 'fips'}, inplace = True)

In [29]:
df1 = pd.merge(df, target_df, how='left', on = 'fips')

In [30]:
df1.isnull().sum()

fips                           0
Pop_Dens                       0
perc_below_pov                 0
perc_unemp                     0
perc_disabled                  0
perc_minority                  0
percent_multiunit_housing      0
perc_overcrowded               0
perc_no_vehicle                0
perc_group_quarters            0
perc_fair_poor_health          0
perc_smokers                   0
perc_obese                     0
perc_phys_inactive             0
prev_hosp_rate_medicare        0
perc_unemployed                0
air_pollution                  0
age_adjusted_mortality         0
perc_diab                      0
perc_insuf_sleep               0
health_costs                   0
med_house_income               0
wnw_seg                        0
Population                     0
perc_fem                       0
perc_rural                     0
pcp_rate_100k                  0
65_older                       0
17_younger                     0
uninsured                      0
lim_eng                        0
cases                        257
deaths                       257
dtype: int64

In [33]:
df1.fillna(value = 0, inplace = True)

df1

,fips,Pop_Dens,perc_below_pov,perc_unemp,perc_disabled,perc_minority,percent_multiunit_housing,perc_overcrowded,perc_no_vehicle,perc_group_quarters,...,Population,perc_fem,perc_rural,pcp_rate_100k,65_older,17_younger,uninsured,lim_eng,cases,deaths
0,1001,92.859967,15.4,4.2,19.3,25.0,3.8,1.4,5.6,1.0,...,55416,51.3,42.0,74.0,14.65,24.30,8.05,0.80,1427.0,82.0
1,1003,130.901947,10.6,4.4,14.0,17.0,18.3,1.3,3.4,1.4,...,208563,51.5,42.3,117.0,19.60,21.80,11.10,0.65,5163.0,110.0
2,1005,29.132150,28.9,9.5,22.2,53.9,1.3,3.4,9.2,11.2,...,25965,46.9,67.8,69.0,18.00,21.10,12.10,1.55,1057.0,13.0
3,1007,36.190214,14.0,7.5,16.7,25.4,2.4,0.8,6.0,9.3,...,22643,46.4,68.4,128.0,15.85,20.75,9.95,0.35,1142.0,4.0
4,1009,89.395591,14.4,4.1,14.2,12.9,0.9,1.6,4.2,0.9,...,57704,50.6,90.0,33.0,17.90,23.30,12.50,1.80,1081.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,56037,4.231045,12.0,5.2,12.3,20.4,5.5,1.9,2.4,1.3,...,44165,48.2,10.9,88.0,10.60,26.85,12.00,1.85,566.0,0.0
3138,56039,5.769301,7.1,1.4,7.0,18.4,7.5,7.2,2.4,4.0,...,23191,48.4,46.4,229.0,13.55,19.00,12.50,3.95,3380.0,19.0
3139,56041,9.899987,12.5,6.1,17.2,12.5,5.8,2.8,3.9,1.3,...,20773,49.4,43.1,106.0,12.35,29.45,12.10,1.00,232.0,0.0
3140,56043,3.631169,12.4,6.2,14.9,18.0,1.1,1.8,5.0,2.0,...,8235,49.7,36.0,97.0,20.80,23.90,16.20,0.50,259.0,0.0
3141,56045,2.960796,17.4,3.5,14.4,8.9,2.6,2.3,2.6,5.1,...,7236,47.3,54.5,110.0,18.80,21.30,13.65,1.00,0.0,0.0

In [58]:
y1 = df1['cases'].values

In [59]:
y2 = df1['deaths'].values

In [60]:
y3_df = (df1['deaths']/df1['cases'])

In [56]:
y3_df.isnull().sum()

257

In [61]:
y3_df.fillna(value=0, inplace = True)

In [62]:
y3_df.isnull().sum()

0

In [63]:
y3 = y3_df.values

In [69]:
Xdf = df.drop(columns = 'FIPS')

In [70]:
X = Xdf.values

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y1)